title: Hacker's Jugad
author: hackers jugad
email: hackersjugad@gmail.com
description:
  > # this means to ignore newlines until "show_exerpts:"# With hacker's jugad you can watch latest movies and web series online without any ads.
  Hi there, We provide latest <strong>web-series, movies</strong> online without any ads. You can also request content with <strong><a href="/request">Request 
  content</a></strong> page. You can list content by clicking on related tag, all tags are 
  available on the bottom of the site.
show_excerpts: false # set to true to show excerpts on the homepage
# baseurl: "https://hackersjugad.github.io"
url: "https://hackersjugad.tech"

# where to write site
#destination: "../site"

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: hackersjugad-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://t.me/hackersjugad
      icon: telegram
      color: blue
    # - url: https://github.com/bitbrain
    #   icon: github-square
    #   color: purple

  show_author: true

  animation_speed: 50

#optimization
#compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->", "// "]
  endings: all
  blanklines: false
  profile: true
  startings: [html, head, body]

# compress sass
sass:
  style: compressed

# Build settings
theme: jekyll-dash

plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-paginate-content

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain

collections:
  books:
    output: true
  movies:
    output: true
  series:
    output: true
# paginate_content:
#   debug: true
#   collections: books, posts

# autopages:
#   enable: true
#   collections:
#     enabled: true
#   tags:
#     enabled: false
