title: Hacker's Jugad
author: Hackers Jugad
email: hackersjugad@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hi there, We provide <strong>web-series, movies</strong> download links, blogs and video tutorials on <strong>hacking, cyber security, linux, unix, and windows</strong> tips and triks. You can request content by going to <strong><a href='/request'>Request content</a></strong> page. You can search content by clicking on related tag, all tags are available on the bottom of the site. 
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: hackersjugad-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://t.me/hackersjugad
      icon: telegram
      color: blue
    # - url: https://github.com/bitbrain
    #   icon: github-square
    #   color: purple

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
 - jekyll-sitemap
 - jekyll-paginate-content
 
# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain


collections:
  books:
    output: true
  mirzapur:
    output: true
  scam1992:
    output: true
  movies:
    output: true
 

# paginate_content:
#   debug: true
#   collections: books, posts

# autopages:
#   enable: true
#   collections:
#     enabled: true
#   tags:
#     enabled: false